CREATE TABLE quotations (
    id SERIAL PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    final_price NUMERIC(10, 2) NOT NULL,
    cpu_details TEXT,
    cpu_price NUMERIC(10, 2),
    cpu_unit INT,
    cpu_upgrade_note TEXT,
    cpu_cooling_details TEXT,
    cpu_cooling_price NUMERIC(10, 2),
    cpu_cooling_unit INT,
    cpu_cooling_upgrade_note TEXT,
    motherboard_details TEXT,
    motherboard_price NUMERIC(10, 2),
    motherboard_unit INT,
    motherboard_upgrade_note TEXT,
    ram_details TEXT,
    ram_price NUMERIC(10, 2),
    ram_unit INT,
    ram_upgrade_note TEXT,
    storage1_details TEXT,
    storage1_price NUMERIC(10, 2),
    storage1_unit INT,
    storage1_upgrade_note TEXT,
    storage2_details TEXT,
    storage2_price NUMERIC(10, 2),
    storage2_unit INT,
    storage2_upgrade_note TEXT,
    gpu_details TEXT,
    gpu_price NUMERIC(10, 2),
    gpu_unit INT,
    gpu_upgrade_note TEXT,
    case_details TEXT,
    case_price NUMERIC(10, 2),
    case_unit INT,
    case_upgrade_note TEXT,
    psu_details TEXT,
    psu_price NUMERIC(10, 2),
    psu_unit INT,
    psu_upgrade_note TEXT,
    sys_fan_details TEXT,
    sys_fan_price NUMERIC(10, 2),
    sys_fan_unit INT,
    sys_fan_upgrade_note TEXT,
    os_details TEXT,
    os_price NUMERIC(10, 2),
    os_unit INT,
    os_upgrade_note TEXT,
    monitor_details TEXT,
    monitor_price NUMERIC(10, 2),
    monitor_unit INT,
    monitor_upgrade_note TEXT,
    others_details TEXT,
    others_price NUMERIC(10, 2),
    others_unit INT,
    others_upgrade_note TEXT,
    platform VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table to store favorite quotations
-- Using a simple approach without user accounts - favorites are shared across all devices
CREATE TABLE favorites (
    id SERIAL PRIMARY KEY,
    quotation_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (quotation_id) REFERENCES quotations(id) ON DELETE CASCADE,
    UNIQUE(quotation_id) -- Prevent duplicate favorites for the same quotation
);
